apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: phonebook
  labels:
    name: mysql-service
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    name: mysql-pod