apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx-service
  namespace: argocd-nginx
spec:
  ports:
  - name: nginx
    port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    app: nginx
  sessionAffinity: None
  type: ClusterIP