apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx-myservice
  namespace: nginx
spec:
  ports:
  - name: nginx
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  sessionAffinity: None
  type: ClusterIP